"""корректировака моделей в бд

Revision ID: 1e9c6d7fe761
Revises: 7c2535c60ea0
Create Date: 2026-07-23 21:34:44.225974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e9c6d7fe761'
down_revision: Union[str, Sequence[str], None] = '7c2535c60ea0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_files_name'), table_name='files')
    op.create_index(op.f('ix_files_name'), 'files', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_files_name'), table_name='files')
    op.create_index(op.f('ix_files_name'), 'files', ['name'], unique=True)
    # ### end Alembic commands ###
