"""empty message

Revision ID: 57546651edb6
Revises: 407e1a9dbed0
Create Date: 2026-07-23 22:43:44.928254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57546651edb6'
down_revision: Union[str, Sequence[str], None] = '407e1a9dbed0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('files', 'zip_data',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('files', 'zip_data',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
