"""корректировака моделей в бд

Revision ID: a697fce6fd34
Revises: 1e9c6d7fe761
Create Date: 2026-07-23 22:34:49.099338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a697fce6fd34'
down_revision: Union[str, Sequence[str], None] = '1e9c6d7fe761'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
